/*
Copyright 2020 The Tilt Dev Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v1alpha1 "github.com/tilt-dev/tilt/pkg/apis/core/v1alpha1"
)

// FakeKubernetesDiscoveries implements KubernetesDiscoveryInterface
type FakeKubernetesDiscoveries struct {
	Fake *FakeTiltV1alpha1
}

var kubernetesdiscoveriesResource = schema.GroupVersionResource{Group: "tilt.dev", Version: "v1alpha1", Resource: "kubernetesdiscoveries"}

var kubernetesdiscoveriesKind = schema.GroupVersionKind{Group: "tilt.dev", Version: "v1alpha1", Kind: "KubernetesDiscovery"}

// Get takes name of the kubernetesDiscovery, and returns the corresponding kubernetesDiscovery object, and an error if there is any.
func (c *FakeKubernetesDiscoveries) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KubernetesDiscovery, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(kubernetesdiscoveriesResource, name), &v1alpha1.KubernetesDiscovery{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KubernetesDiscovery), err
}

// List takes label and field selectors, and returns the list of KubernetesDiscoveries that match those selectors.
func (c *FakeKubernetesDiscoveries) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KubernetesDiscoveryList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(kubernetesdiscoveriesResource, kubernetesdiscoveriesKind, opts), &v1alpha1.KubernetesDiscoveryList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KubernetesDiscoveryList{ListMeta: obj.(*v1alpha1.KubernetesDiscoveryList).ListMeta}
	for _, item := range obj.(*v1alpha1.KubernetesDiscoveryList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kubernetesDiscoveries.
func (c *FakeKubernetesDiscoveries) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(kubernetesdiscoveriesResource, opts))
}

// Create takes the representation of a kubernetesDiscovery and creates it.  Returns the server's representation of the kubernetesDiscovery, and an error, if there is any.
func (c *FakeKubernetesDiscoveries) Create(ctx context.Context, kubernetesDiscovery *v1alpha1.KubernetesDiscovery, opts v1.CreateOptions) (result *v1alpha1.KubernetesDiscovery, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(kubernetesdiscoveriesResource, kubernetesDiscovery), &v1alpha1.KubernetesDiscovery{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KubernetesDiscovery), err
}

// Update takes the representation of a kubernetesDiscovery and updates it. Returns the server's representation of the kubernetesDiscovery, and an error, if there is any.
func (c *FakeKubernetesDiscoveries) Update(ctx context.Context, kubernetesDiscovery *v1alpha1.KubernetesDiscovery, opts v1.UpdateOptions) (result *v1alpha1.KubernetesDiscovery, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(kubernetesdiscoveriesResource, kubernetesDiscovery), &v1alpha1.KubernetesDiscovery{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KubernetesDiscovery), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKubernetesDiscoveries) UpdateStatus(ctx context.Context, kubernetesDiscovery *v1alpha1.KubernetesDiscovery, opts v1.UpdateOptions) (*v1alpha1.KubernetesDiscovery, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(kubernetesdiscoveriesResource, "status", kubernetesDiscovery), &v1alpha1.KubernetesDiscovery{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KubernetesDiscovery), err
}

// Delete takes name of the kubernetesDiscovery and deletes it. Returns an error if one occurs.
func (c *FakeKubernetesDiscoveries) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(kubernetesdiscoveriesResource, name), &v1alpha1.KubernetesDiscovery{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKubernetesDiscoveries) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(kubernetesdiscoveriesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.KubernetesDiscoveryList{})
	return err
}

// Patch applies the patch and returns the patched kubernetesDiscovery.
func (c *FakeKubernetesDiscoveries) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KubernetesDiscovery, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(kubernetesdiscoveriesResource, name, pt, data, subresources...), &v1alpha1.KubernetesDiscovery{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KubernetesDiscovery), err
}
